### PR TITLE
Remove AdbClient.Instance

### PR DESCRIPTION
**Pull request by qmfrederik**
An `IAdbClient` object wraps around one or more a unique connections to an adb server. This connection is not intended to be shared; and storing it in a static can cause all kinds of mayhem (not in the least in unit tests).

This commit completely removes the `AdbClient.Instance` static.

Code which used to rely on `AdbClient.Instance` will now need to explictely pass the `IAdbClient` object. This makes it much more clear that you are operating on an adb connection.

For example:

```
device.ExecuteShellCommand(...)
```

now becomes
```
client.ExecuteShellCommand(device, ...)
```

making it much more explicit over which connection channel you are operating.

### CODE REVIEW

**Comment by 5p134n** [comment]
What will this code look like in this case ?

var devices = AdbClient.Instance.GetDevices();
foreach(var device in devices)
{
    Console.WriteLine(device.Name);
}

**Comment by qmfrederik** [comment]
Something like this:

```csharp
var client = new AdbClient();
var devices = client.GetDevices();

foreach(var device in devices)
{
    Console.WriteLine(device.Name);
}
```
```

**Comment by 5p134n** [comment]
Thank you

**Comment by seltix5** [comment]
> ```cs
> var client = new AdbClient();
> var devices = client.GetDevices();
> ```

that should be on the home page, thanks!

**Comment by seltix5** [comment]
> ```cs
> var client = new AdbClient();
> var devices = client.GetDevices();
> ```

that should be on the home page, thanks!

**Pull request merged**
